version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: testBD
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local