name: Build, Test and Deploy to Remote Server

# Триггер для запуска пайплайна
on:
  push:
    branches:
      - main

jobs:
  build:
    # Задача запускается на ОС ubuntu
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 5432:5432

    steps:
      # Это действие извлекает ваш репозиторий из папки $GITHUB_WORKSPACE,
      #  чтобы ваш рабочий процесс мог получить к нему доступ.
      - uses: actions/checkout@v3

      # Настройки java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Права на запуск gradlew
      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      # билд проекта
      - name: Build project
        run: ./gradlew build


  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      # Тест проекта
      - name: Run tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    # Для запуска требуется прохождение тестов
    needs: test

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build the project (again for deploy)
        run: ./gradlew build

      # Настройка SSH клиента
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

#      # Убиваем старый процесс с таким же работающим именем
#      - name: kill old app
#        run: |
#          ssh -o StrictHostKeyChecking=no root@212.67.11.228 'pkill -f short-links-0.0.1-SNAPSHOT.jar || true'

      # Копируем файл, который запустит приложение, в папку short-links на удаленном сервере
      - name: Copy files to remote server
        run: |
          scp -o StrictHostKeyChecking=no build/libs/short-links-0.0.1-SNAPSHOT.jar root@212.67.11.228:short-links/

      # Запускаем новый файл
      - name: run new app
        run: |
          ssh -o StrictHostKeyChecking=no root@212.67.11.228 'nohup java -jar short-links/short-links-0.0.1-SNAPSHOT.jar > app.log 2>&1 &'